### ISSUE TITLE
make it compatible with TCC

### ISSUE THREAD

**Issue by CardealRusso** [neroist/webui#4]
tcc: error: library 'ws2_32' not found

**Comment by CardealRusso** [comment]
[i get ws2_32](tcc: error: library 'ws2_32' not found)

**Comment by CardealRusso** [comment]
i dont get it. i can compile the c example with tcc but on nim i get ws2 not found

**Comment by neroist** [comment]
Do you have `libws2_32.a` on your system? That seems to be the issue.

**Comment by neroist** [comment]
I think it can be installed by downloading the Windows 8.1/10/11 SDK, though I'm not too sure.

**Comment by CardealRusso** [comment]
> The TCC [Make file](https://github.com/alifcommunity/webui/blob/d02eead1a9af28292dadeed6f88d16afb8b1fd99/build/Windows/TCC/Makefile#LL20C56-L20C64) in WebUI use `-lws2_32` to link the Windows Socket library. And it seems [bindings.nim](https://github.com/neroist/webui/blob/14016f0ed132c1d88900ec8cab14d4070bc024c0/webui/bindings.nim#LL59C15-L59C23) also use `-lws2_32`.
> 
> You should download the latest [mob development branch of TCC](https://github.com/TinyCC/tinycc), as the official one was abandoned a while ago. And build it using `build-tcc.bat`.
> 
> On the other hand, if you can build WebUI using TCC, there is probably something wrong with `bindings.nim`.

yes indeed i can compile the c99 example with tcc without any problem
im already using the mob version of tcc

**Comment by AlbertShown** [comment]
The issue is with `bindings.nim`. We will fix it soon.
