### ISSUE TITLE
Question about License

### ISSUE THREAD

**Issue by AlbertShown** [neroist/webui#6]
Why did you choose MIT License? Is there any benefit over the GPL one?

**Comment by neroist** [comment]
I chose it because its the fist license that comes up when you do `nimble init`. I want to change it but I'm not sure if you can change the license in `packages.json`

**Comment by AlbertShown** [comment]
According to [to this](https://github.com/alifcommunity/webui/issues/61#issuecomment-1488521715). We should follow the exact license GPLv2.0. It's not a big deal. I want to let you know.

**Comment by AlbertShown** [comment]
Probably If you update the license file in GitHub, commit, push, then push the package to nimble, the license will also be updated in https://nimble.directory.

**Comment by neroist** [comment]
Made a PR here: https://github.com/nim-lang/packages/pull/2555

**Comment by AlbertShown** [comment]
https://github.com/nim-lang/packages/pull/2555 is merged. Thank you 👍
